### ISSUE TITLE
Synchronization

### ISSUE THREAD

**Issue by aerograf** [XoopsModules25x/tag#15]
During synchronization, the following loops:
```
Invalid page redirection
Firefox has determined that the server redirects the request to this address in such a way that it never ends.
This problem can occur when the cookie is disabled or disabled.
```

**Comment by mambax7** [comment]
Can you check with the current changes here, if this is still the case?

**Comment by aerograf** [comment]
Yes. In the near future I will check.

**Comment by aerograf** [comment]
It worked. But it is necessary to pay attention that it is MANDATORY to check the localization files in the repositories, otherwise the module with other languages will not work!
There is a small error message:
Notification: Undefined offset: 57 in / modules/tag/admin/index.php line 72
Notification: Undefined offset: 225 in / modules/tag/admin/index.php line 72

**Comment by aerograf** [comment]
https://github.com/XoopsLanguages/russian/tree/master/modules/tag/2.34%20RC-2

**Comment by mambax7** [comment]
Please reopen, if this is still an issue
