### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/tag#17]
i want to test but i can't install the module i received blank page turn on the debug no error

Tag 2.33 RC 1
XOOPS Version | XOOPS 2.5.10-Beta
PHP Version | 5.6.25
mySQL Version | 5.7.14

**Comment by liomj** [comment]
i tried mamba's fork https://github.com/mambax7/tag 
it can be installed thank you

**Comment by mambax7** [comment]
I'm glad that it works for you.
I just merged my changes here, so please update your fork, and report any issues here. 
Thank you!
