### ISSUE TITLE
Call to a member function getVar() on null

### ISSUE THREAD

**Issue by geekwright** [XoopsModules25x/tag#23]
Originally report in XOOPS/XoopsCore25#773

The user added the tag module to the modules directory to include it in a fresh install of XoopsCore25. This caused a fatal error.

The tag module is assuming a context and modifying language constants with that context.
In the installer context `$GLOBALS['xoopsModule']` is not set, and thus cannot be used.

This is the line:
```
define('_AM_TAG_ADMIN_FOOTER', "<div class='right smallsmall italic pad5'><b>" . $GLOBALS['xoopsModule']->getVar('name') . "</b> is maintained by the <a class='tooltip' rel='external' href='https://xoops.org/' title='Visit XOOPS Community'>XOOPS Community</a></div>");
```

The resulting errors are:
```
Notice: Undefined index: xoopsModule in file /modules/tag/language/english/admin.php line 80
Error: Error: Call to a member function getVar() on null in file /modules/tag/language/english/admin.php line 80
```

**Comment by mambax7** [comment]
Thanks! I'll look into it this weekend.

**Comment by mambax7** [comment]
I believe that Zyspec has already fixed that issue in https://github.com/XoopsModules25x/tag/commit/f4206d711f9fd626247100af23d9c3ec274e0deb#diff-ad76662c85d89b38e141a35bd57b9e8d
