### ISSUE TITLE
Problem when deleting content

### ISSUE THREAD

**Issue by GregMage** [XoopsModules25x/tag#25]
Problem when deleting content
Why is there no function to delete a tag? I am trying to put this module in xmnews and it gives me problem (modules / tag / view.tag.php / tag). I add a news with tags and it works. I add a 2nd news with the same tags and it works too. On the other hand, I destroy my news 1 and the cited page crashes. Normal, he is looking for non-existent news.

You need a function to remove the links between the news and the tags if you delete a news ...
The module as thought is not usable without it.

**Comment by mambax7** [comment]
Wouldn't synchronization delete the tags from non existent news? 

How can you reproduce the behavior step by step, and what behavior do you expect when you delete the News1? 

1) You create News1 and add tags
2) You create News2 and add the same tags
3) You delete News 1, and which page crashes? The one of News2? Or the one of Tag? If Tag, is this the front general page, the front-page with that particular tag, or the Admin page?

I need to replicate it to see what is happening..

**Comment by GregMage** [comment]
it's the tag module that crashes, not my module!

Simple, you put for example the tag: "text" in 2 contents. Then you go to this page: "modules / tag / view.tag.php / test

everything works, then you remove some content and that same page crashes. This is normal because it wants to link content that does not exist, tag must provide a system to remove links from tags when deleting. Another question, what is the syncronization page for in the admin? And the syncronization function in a plugin? It doesn't seem to work ...

**Comment by mambax7** [comment]
I just tested with Publisher by doing as you said, i.e. adding tags to two articles, then going to /modules/tag/view.tag.php, and everything works. 
Then I deleted one of the articles, and went to refresh the Tag page, and everything was working fine. I actually had two pages, one with a tag that was only in the deleted article, and one with a tag in both. 
The page with the unique tag only gave me a notice about "Invalid Query" and redirected to /modules/tag/index.php

![image](https://user-images.githubusercontent.com/613686/144814586-286c067e-a500-41ce-9aed-5d4b54517978.png)
The other page, when I refreshed it, showed me the correct list of tags and the other article. 

I tested it locally on my PC and on PHP 8.1

**Comment by GregMage** [comment]
It's okay, publisher is doing it right. The problem comes from the documentation which does not explain that we must call the "updateByItem" function when deleting a content.
I had done different for the same result but I will use the publisher method.

Can you tell me about syncronization?

**Comment by mambax7** [comment]
My understanding is that synchronization page in the admin was to update the current links in case they got out of sync with the modules. But I didn't investigate it in depth...
