### ISSUE TITLE
Just a discussion room

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/tag#30]
Working on bt4 tpl

1st step:

![Capture d’écran 2021-12-10 210641](https://user-images.githubusercontent.com/5336960/145635079-a7104a5f-2cdc-4ea4-a676-55b19b4e8da6.png)

**Comment by alain01** [comment]
<{$article.content}> is empty, 
normal ?

**Comment by alain01** [comment]
<{$module_name}> is unknown in the tag_index.tpl file but it's ok in the tag_view.tpl
Please, could you correct this (in the php file I think)

**Comment by mambax7** [comment]
Which module are you using, and what version? Is it Publisher? News? xmNews?

**Comment by alain01** [comment]
Version de XOOPS | XOOPS 2.5.11-Beta2
-- | --
Version de PHP | 7.3.25
Version de mySQL | 8.0.16

tag from https://github.com/mambax7/tag (master / 2.35.0Beta 4)
publisher 1.8 alpha.6
xmnews (master)

**Comment by mambax7** [comment]
But which module has these issues that you describe, like the <{$article.content}>
If I test it, I need to know exactly how can I reproduce it, so please be specific about the problem, which modules are involved, and what steps I need to do to reproduce it...

**Comment by alain01** [comment]
ok
label name for xmnews is Articles
label name for publisher is "ma publication"
label name for tag is "tag et mots clés"

in tag_view.tpl, we used 
<li class="breadcrumb-item"><span class="fa fa-tags text-secondary fa-lg fa-fw mr-2 mt-1"></span><a href="index.php"><{$module_name}></a></li>
and it's ok in the breadcrumb, 

<{$module_name}> => tag et mots clés

but in the tag_index.tpl, 
missing the line <li class="breadcrumb-item"><span class="fa fa-tags text-secondary fa-lg fa-fw mr-2 mt-1"></span><a href="index.php"><{$module_name}></a></li>

when I Added it, the smarty <{$module_name}> is unknown

**Comment by mambax7** [comment]
Check in the "default" theme, if you have the some problems. Sometimes there are issues with the templates in various themes.

**Comment by alain01** [comment]
No...
see my printscreen , the breadcrum : 
"tag et mots clés" (for the "tag module name")

**Comment by alain01** [comment]
File tag_view.tpl : 
```
<ol class="breadcrumb" >
    <li class="breadcrumb-item"><span class="fa fa-tags text-secondary fa-lg fa-fw mr-2 mt-1"></span><a href="index.php"><{$module_name}></a></li>
    <li class="breadcrumb-item"><a href="<{$xoops_url}>/modules/<{$xoops_dirname}>/list.tag.php" title="<{$smarty.const._MD_TAG_TAGS}>"><{$smarty.const._MD_TAG_TAGS}></a></li>
    <li class="breadcrumb-item active" aria-current="page"><{$tag_term}></li>
</ol>
```

![Capture d’écran 2021-12-10 215556](https://user-images.githubusercontent.com/5336960/145640266-235556d4-d0a2-4290-b7c4-9ff1d2e4d6da.png)

It's ok here, this smarty <{$module_name}> gives "tag et mots clés"


Now,
file tag_index.tpl

```<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<{$xoops_url}>/modules/<{$xoops_dirname}>/" title="<{$smarty.const._MD_TAG_TAGS}>"><{$smarty.const._MD_TAG_TAGS}></a></li>
    <li class="breadcrumb-item active"><a href="<{$xoops_url}>/modules/<{$xoops_dirname}>/list.tag.php<{$smarty.const.URL_DELIMITER}><{$tag_term}>" title="<{$tag_page_title|strip_tags}>" rel="tag"><{$tag_page_title|regex_replace:'/^.+g>/U':''|replace:'</strong>':''}></a></li>
</ol>

```

Missing the line for the label of the module
so I added 
`<li class="breadcrumb-item"><span class="fa fa-tags text-secondary fa-lg fa-fw mr-2 mt-1"></span><a href="index.php"><{$module_name}></a></li>`

so the code is 
```
  <ol class="breadcrumb" >
    <li class="breadcrumb-item"><span class="fa fa-tags text-secondary fa-lg fa-fw mr-2 mt-1"></span><a href="index.php"><{$module_name}></a></li>
    <li class="breadcrumb-item"><a href="<{$xoops_url}>/modules/<{$xoops_dirname}>/list.tag.php" title="<{$smarty.const._MD_TAG_TAGS}>"><{$smarty.const._MD_TAG_TAGS}></a></li>
    <li class="breadcrumb-item active"><a href="<{$xoops_url}>/modules/<{$xoops_dirname}>/list.tag.php<{$smarty.const.URL_DELIMITER}><{$tag_term}>" title="<{$tag_page_title|strip_tags}>" rel="tag"><{$tag_page_title|regex_replace:'/^.+g>/U':''|replace:'</strong>':''}></a></li>
  </ol>

```

but this line shows nothing, this smarty <{$module_name}> is unknown in this template, so the result is:


![Capture d’écran 2021-12-10 220645](https://user-images.githubusercontent.com/5336960/145641371-88b481df-abc9-4ca0-a666-0f7350a7bc28.png)

**Comment by mambax7** [comment]
I'll look into it later tonight...

**Comment by alain01** [comment]
ok no pb :-)

**Comment by mambax7** [comment]
1) > <{$article.content}> is empty,

Yes, for publisher and for xmNews, the content is empty. I guess, the decision was that the content could be very big, so in order to make it more responsive, the Tag module shows only the article titles and the user can then go and check out the article directly. 

I tested it with Publisher, by pulling the "summary" as content, and as you can see, it could become very big:

![image](https://user-images.githubusercontent.com/613686/145664620-bfdea340-a533-438c-a90e-0e45da4cf0b2.png)


2) $module_name in tag_index.tpl

in index.php add 

` 'module_name'            => $GLOBALS['xoopsModule']->getVar('name'),`

to the `$GLOBALS['xoopsTpl']->assign(` section

```php
$GLOBALS['xoopsTpl']->assign(
    [
        'module_name'            => $GLOBALS['xoopsModule']->getVar('name'),
```

**Comment by alain01** [comment]
ok, I prefered empty field too,
I've just notice that ! ;-)

**Comment by mambax7** [comment]
I've uploaded the changes to https://github.com/mambax7/tag

**Comment by alain01** [comment]
Amazing ! 
The non-stop XOOPS Team 24/24 !

**Comment by alain01** [comment]
Why closed this discussion ?
The issue https://github.com/XoopsModules25x/tag/issues/30#issuecomment-991294126 is open
Read the whole comment for a full explanation

![Capture d’écran 2021-12-10 220645](https://user-images.githubusercontent.com/5336960/145641371-88b481df-abc9-4ca0-a666-0f7350a7bc28.png)

**Comment by alain01** [comment]
In other words, I need to use the <{$module_name}> in all the tpl file (not block), for the breadcrumb

It is present only in the tag_view.tpl
`<li class="breadcrumb-item"><a href="<{$xoops_url}>/modules/<{$xoops_dirname}>/" title="<{$module_name}>"><{$module_name}></a></li>`

So I need to use this smarty for this templates too
- tag_list.tpl 
- tag_index.tpl

**Comment by mambax7** [comment]
I already gave you the solution above, and I even committed it to GitHub:

![image](https://user-images.githubusercontent.com/613686/145672318-ff2c5a26-f9ee-49b8-83b5-fc8e921365b2.png)

And you didn't say anything about tag_list.tpl

So based on the above you could add the solution to list.tag.php and submit to my repository :)

**Comment by mambax7** [comment]
I've already added it to index.php, and right now I also added it to list.tag.php:
https://github.com/mambax7/tag/commit/91c2179f9faede0f5c72b8ca18cdb6b822fdf9e7

**Comment by alain01** [comment]
Ok super, Mamba! 
I know it's difficult with a non-developer...
I'm on it.

**Comment by mambax7** [comment]
no problem! :)
