### ISSUE TITLE
Tag with accent - Problem

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/tag#31]
Tag : randonnées 
Résult : 
![Capture d’écran 2021-12-10 230055](https://user-images.githubusercontent.com/5336960/145647060-484c7d8c-1e4c-492a-9070-a0af10594096.png)

**Comment by mambax7** [comment]
Works here with Publisher without any problems:
![image](https://user-images.githubusercontent.com/613686/145663080-8981afd1-9118-4d00-ba93-b8a20e1ec850.png)

**Comment by alain01** [comment]
1 of these smarty is wrong : 
<{$tag_term}> - <{$tag_title}>

Fen%C3%AAtre - Fenêtre

**Comment by mambax7** [comment]
I am using the xswatch4 from https://github.com/XOOPS/XoopsCore25, and with Publisher is working just fine. 
So maybe something is wrong in your new templates?

**Comment by alain01** [comment]
Yes I used the the <{$tag_term}>, not <{$tag_title}>.
<{$tag_term}> is for the URL

`<li class="breadcrumb-item active"><a href="<{$xoops_url}>/modules/<{$xoops_dirname}>/view.tag.php<{$smarty.const.URL_DELIMITER}><{$tag_term}>" title="<{$tag_title}>" rel="tag"><{$tag_title}></a></li>`

<{$tag_term}> **is only for the URL**, not to display the name of the tag.

Sorry, my bad.
I closed it.

**Comment by mambax7** [comment]
Excellent! 
Anything else, or should we release Beta 4?

**Comment by mambax7** [comment]
Or maybe even RC-1 ? :)

**Comment by alain01** [comment]
I'm not ready for the new template but you could see my 1st step here: 
![Capture d’écran 2021-12-10 210641](https://user-images.githubusercontent.com/5336960/145635079-a7104a5f-2cdc-4ea4-a676-55b19b4e8da6.png)

yes, for the next release... ;-)
