### ISSUE TITLE
error cumulus tag Cloud

### ISSUE THREAD

**Issue by GregMage** [XoopsModules25x/tag#33]
If I want to edit the block: 

Erreur: Error: Call to undefined function tag_block_cumulus_edit() dans le fichier /modules/system/class/block.php ligne 221

**Comment by alain01** [comment]
Humm
Please, test tag with the latest version from Mamba here : https://github.com/mambax7/tag

This bloc hab been desactivated, see my issue [flash block](https://github.com/mambax7/tag/issues/14) 
and the merged PR [delete cumulus.swf files](https://github.com/mambax7/tag/commit/e5b4e48b6d37acb8da7e6cc094bbcbc412f76e14)

**Comment by mambax7** [comment]
This block is gone in the latest version
